site_name: ADAPT
site_url: "https://kitware.github.io/adapt/"
theme:
    name: material
    features:
        - navigation.top
    logo: img/adapt_white.png
    favicon: img/adapt.png

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
        toc_depth : "1-1"

nav:
    - Home: index.md
    - About: about.md
    - Get Started: get_started.md
    - Structure: structure.md
    - Latest updates: blog.md
    - Payload Components : parts.md
    - Example Missions: missions.md
    - Provisioning:
        - Overview: provisioning.md
        - ADAPT software stack: prov1.md
        - 1PPS hardware input: prov2.md
        - Configure time server: prov3.md
        - PTP server: prov4.md
        - Automatic startup: prov5.md
    - Frequently Asked Questions: faq.md
    - Contact Us: contact.md

repo_url: https://gitlab.kitware.com/adapt/adapt
repo_name: Gitlab ADAPT repo
