site_name: ADAPT
site_url: "https://kitware.github.io/adapt/"
site_description: Documentation for the ADAPT payload
site_author: Kitware
theme:
    name: material
    features:
        - navigation.top
    logo: img/adapt_white.png
    favicon: img/adapt.png

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
        toc_depth : "1-1"

plugins:
    - mkdocs-video

nav:
    - Home: index.md
    - About: about.md
    - Get Started: get_started.md
    - Structure: structure.md
    - Latest updates: blog.md
    - Payload Components : parts.md
    - Example Missions:
        - Missions: missions.md
        - Sea and River Ice Monitoring: ice_monitor.md
        - Monitoring Arctic Mammal Populations: ice_seal.md
        - Person Search and Rescue: search_and_rescue.md
        - Wild Fire Monitoring: fire_monitoring.md
        - Flood Monitoring: flood_monitoring.md
        - Coastline Erosion Monitoring: coastline_monitoring.md
    - Provisioning:
        - Overview: provisioning.md
        - ADAPT software stack: prov1.md
        - 1PPS hardware input: prov2.md
        - Configure time server: prov3.md
        - PTP server: prov4.md
        - Automatic startup: prov5.md
    - Presentations: presentations.md
    - Frequently Asked Questions: faq.md
    - Contact Us: contact.md

repo_url: https://gitlab.kitware.com/adapt/adapt
repo_name: Gitlab ADAPT repo

extra:
  analytics:
    provider: google
    property: G-G39JGPMQEQ
  consent:
    title: Cookie consent
    description: >
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
